# Generated by Django 4.0.5 on 2022-06-05 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('postCode', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('paymentDue', models.DateField(blank=True, null=True)),
                ('description', models.TextField(null=True)),
                ('paymentTerms', models.IntegerField(null=True)),
                ('clientName', models.CharField(max_length=200, null=True)),
                ('clientEmail', models.EmailField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Paid', 'Paid'), ('', '')], default='', max_length=10)),
                ('total', models.FloatField(default=0.0, null=True)),
                ('client_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.clientaddress')),
            ],
        ),
        migrations.CreateModel(
            name='senderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('postCode', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('quantity', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=200, null=True)),
                ('total', models.CharField(max_length=200, null=True)),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='invoice.invoice')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='sender_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.senderaddress'),
        ),
    ]
